packages:
  - "apps/*"
  - "packages/*"
  - "tests/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "argon2"
  - "esbuild"
  - "prisma"
  - "sharp"
  - "unrs-resolver"
  - "workerd"
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@scarf/scarf": false
  argon2: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true
